// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "fireModelingServiceTut",
            "endpoint": "https://mjh6ct171e.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "modeling-service-tutorials.wfmrda.com",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://modeling-service-tutorials.wfmrda.com.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
